# Generated by Django 5.1.6 on 2025-03-06 00:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('mines', models.IntegerField()),
                ('board_state', models.JSONField(blank=True, null=True)),
                ('revealed_cells', models.IntegerField(default=0)),
                ('game_over', models.BooleanField(default=False)),
                ('game_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
