# Generated by Django 5.1.6 on 2025-03-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='board_state',
            new_name='internal_board',
        ),
        migrations.AddField(
            model_name='game',
            name='player_board',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
